# Generated by Django 5.2.8 on 2026-03-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_alter_service_full_description_servicesubservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL friendly name, e.g. virtual-cfo', unique=True),
        ),
    ]
