name: Deploy Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: SSH Deploy
      uses: appleboy/ssh-action@v0.1.7

      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}

        script: |
          cd /home/ubuntu/backend-app
          git pull origin main

          source venv/bin/activate
          pip install -r requirements.txt

          python manage.py migrate
          python manage.py collectstatic --noinput

          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
